spread: expect chisel failure
Instead of disabling the test altogether, consider it a success if it
fails because of the expected reason (Chisel bug with dotnet packages).
All other scenarios (successful pack, or failure for a different reason)
are a failure - this will let us know when the bug is fixed!

Ref:
- https://github.com/canonical/chisel-releases/pull/23

diff --git a/tests/spread/general/chisel/task.yaml b/tests/spread/general/chisel/task.yaml
--- a/tests/spread/general/chisel/task.yaml
+++ b/tests/spread/general/chisel/task.yaml
@@ -1,7 +1,28 @@
 summary: a test that checks ROCKs created with Chisel slices
 
 execute: |
-  rockcraft pack
+
+  # NOTE: packing is currently failing here because of dotnet-host changes:
+  # https://github.com/canonical/chisel-releases/pull/23
+  # Instead of disabling the test altogether, we let it pass *if and only if* packing
+  # failed because of the bug.
+  # The commit that adds this code can be reverted once the Chisel bug is fixed.
+  if rockcraft pack; then
+    echo "rockcraft pack succeeded unexpectedly!"
+    exit 1
+  else
+    # Find the "latest" log file to parse the error message
+    log_file=$(find /root/.cache/rockcraft/log/ -iname "rockcraft*.log" | sort -r | head -n1)
+
+    # "rockcraft pack" must only have failed because of the Chisel bug
+    expected_error="Command '\['chisel', 'cut', '--root', '/root/parts/chisel-part/install', 'dotnet-runtime-6.0_libs'\]' returned non-zero exit status 1"
+
+    grep "$expected_error" $log_file
+
+    # Failed for the expected reason, finish the test successfully
+    echo "'rockcraft pack' failed as expected because of a Chisel bug with dotnet; considering success."
+    exit 0
+  fi
 
   ROCK=`ls *.rock`
   IMG_NAME=chiselled-image
