Chore(): Rework spread test

diff --git a/tests/spread/rockcraft/extension-django/task.yaml b/tests/spread/rockcraft/extension-django/task.yaml
--- a/tests/spread/rockcraft/extension-django/task.yaml
+++ b/tests/spread/rockcraft/extension-django/task.yaml
@@ -38,23 +38,16 @@ execute: |
   docker run --rm --entrypoint /bin/python3 example-django -c "import pathlib;assert pathlib.Path('/django/app/manage.py').is_file()"
   docker run --rm --entrypoint /bin/python3 example-django -c "import pathlib;assert pathlib.Path('/django/app/.foobar').is_file()"
 
-  # ensure the django folder has the correct user
-  docker run --rm --entrypoint /bin/bash "${IMAGE}" -c "find /django -exec ls -ld {} \;" | awk '$3 != "_daemon_" {print; exit 2}'
-  if [ $? -eq 2 ]; then
-    echo "Error: Some files/folders inside /django are not owned by _daemon_"
-    exit 2
-  fi
-  # ensure the loki log folder has the correct user
-  docker run --rm --entrypoint /bin/bash "${IMAGE}" -c "find /opt/promtail -exec ls -ld {} \;" | awk '$3 != "_daemon_" {print; exit 2}'
-  if [ $? -eq 2 ]; then
-    echo "Error: Some files/folders inside /opt/promtail are not owned by _daemon_"
-    exit 2
-  fi
-  docker run --rm --entrypoint /bin/bash "${IMAGE}" -c "find /etc/promtail -exec ls -ld {} \;" | awk '$3 != "_daemon_" {print; exit 2}'
-  if [ $? -eq 2 ]; then
-    echo "Error: Some files/folders inside /etc/promtail are not owned by _daemon_"
-    exit 2
-  fi
+  # ensure the django and promtail folders have the correct user
+  check_directory_ownership() {
+    local directory="$1"
+    docker run --rm --entrypoint /bin/bash "${IMAGE}" -c "find ${directory} -exec stat -c '%U' {} + | grep -q '^_daemon_$' || { echo 'Error: ${directory} or its contents are not owned by _daemon_'; exit 2; }"
+  }
+
+  check_directory_ownership "/django"
+  check_directory_ownership "/opt/promtail"
+  check_directory_ownership "/etc/promtail"
+
   # test the default django service
   docker run --name example-django-container -d -p 8138:8000 example-django
   retry -n 5 --wait 2 curl localhost:8138
diff --git a/tests/spread/rockcraft/extension-fastapi/task.yaml b/tests/spread/rockcraft/extension-fastapi/task.yaml
--- a/tests/spread/rockcraft/extension-fastapi/task.yaml
+++ b/tests/spread/rockcraft/extension-fastapi/task.yaml
@@ -32,24 +32,15 @@ execute: |
   # ensure container doesn't exist
   docker rm -f "${NAME}-container"
 
-  # ensure the app folder has the correct user
-  docker run --rm --entrypoint /bin/bash "${IMAGE}" -c "find /app -exec ls -ld {} \;" | awk '$3 != "_daemon_" {print; exit 2}'
-  if [ $? -eq 2 ]; then
-    echo "Error: Some files/folders inside app are not owned by _daemon_"
-    exit 2
-  fi
+  # ensure the app and promtail folders have the correct user
+  check_directory_ownership() {
+    local directory="$1"
+    docker run --rm --entrypoint /bin/bash "${IMAGE}" -c "find ${directory} -exec stat -c '%U' {} + | grep -q '^_daemon_$' || { echo 'Error: ${directory} or its contents are not owned by _daemon_'; exit 2; }"
+  }
 
-  # ensure the loki log folder has the correct user
-  docker run --rm --entrypoint /bin/bash "${IMAGE}" -c "find /opt/promtail -exec ls -ld {} \;" | awk '$3 != "_daemon_" {print; exit 2}'
-  if [ $? -eq 2 ]; then
-    echo "Error: Some files/folders inside /opt/promtail are not owned by _daemon_"
-    exit 2
-  fi
-  docker run --rm --entrypoint /bin/bash "${IMAGE}" -c "find /etc/promtail -exec ls -ld {} \;" | awk '$3 != "_daemon_" {print; exit 2}'
-  if [ $? -eq 2 ]; then
-    echo "Error: Some files/folders inside /etc/promtail are not owned by _daemon_"
-    exit 2
-  fi
+  check_directory_ownership "/app"
+  check_directory_ownership "/opt/promtail"
+  check_directory_ownership "/etc/promtail"
 
   # test the default fastapi service
   docker run --name "${NAME}-container" -d -p 8137:8000 "${IMAGE}"
diff --git a/tests/spread/rockcraft/extension-flask/task.yaml b/tests/spread/rockcraft/extension-flask/task.yaml
--- a/tests/spread/rockcraft/extension-flask/task.yaml
+++ b/tests/spread/rockcraft/extension-flask/task.yaml
@@ -35,23 +35,15 @@ execute: |
   docker run --rm --entrypoint /bin/python3 "${IMAGE}" -c "import pathlib;assert pathlib.Path('/flask/app/static/js/test.js').is_file()"
   docker run --rm --entrypoint /bin/python3 "${IMAGE}" -c "import pathlib;assert not pathlib.Path('/flask/app/node_modules').exists()"
 
-  # ensure the flask folder has the correct user
-  docker run --rm --entrypoint /bin/bash "${IMAGE}" -c "find /flask -exec ls -ld {} \;" | awk '$3 != "_daemon_" {print; exit 2}'
-  if [ $? -eq 2 ]; then
-    echo "Error: Some files/folders inside /flask are not owned by _daemon_"
-    exit 2
-  fi
-  # ensure the loki log folder has the correct user
-  docker run --rm --entrypoint /bin/bash "${IMAGE}" -c "find /opt/promtail -exec ls -ld {} \;" | awk '$3 != "_daemon_" {print; exit 2}'
-  if [ $? -eq 2 ]; then
-    echo "Error: Some files/folders inside /opt/promtail are not owned by _daemon_"
-    exit 2
-  fi
-  docker run --rm --entrypoint /bin/bash "${IMAGE}" -c "find /etc/promtail -exec ls -ld {} \;" | awk '$3 != "_daemon_" {print; exit 2}'
-  if [ $? -eq 2 ]; then
-    echo "Error: Some files/folders inside /etc/promtail are not owned by _daemon_"
-    exit 2
-  fi
+  # ensure the flask and promtail folders have the correct user
+  check_directory_ownership() {
+    local directory="$1"
+    docker run --rm --entrypoint /bin/bash "${IMAGE}" -c "find ${directory} -exec stat -c '%U' {} + | grep -q '^_daemon_$' || { echo 'Error: ${directory} or its contents are not owned by _daemon_'; exit 2; }"
+  }
+
+  check_directory_ownership "/flask"
+  check_directory_ownership "/opt/promtail"
+  check_directory_ownership "/etc/promtail"
 
   # test the default flask service
   docker run --name "${NAME}-container" -d -p 8137:8000 "${IMAGE}"
