test(spread): migrate from google to openstack

diff --git a/.github/workflows/spread.yaml b/.github/workflows/spread.yaml
--- a/.github/workflows/spread.yaml
+++ b/.github/workflows/spread.yaml
@@ -38,7 +38,7 @@ jobs:
           path: ${{ steps.rockcraft.outputs.snap }}
 
   source-spread-tests:
-    runs-on: [self-hosted, spread-installed]
+    runs-on: [self-hosted, spread-enabled]
     needs: [snap-build]
     if: ${{ needs.snap-build.outputs.source-files == 'true' || github.event_name == 'schedule' }}
 
@@ -58,24 +58,24 @@ jobs:
           name: snap
           path: tests
 
-      - name: Run Ubuntu Pro spread tests
-        env:
-          UBUNTU_PRO_TOKEN: ${{ secrets.UBUNTU_PRO_TOKEN }}
-        run: |
-          if [ -z "$UBUNTU_PRO_TOKEN" ]; then
-            if [ "${{ github.event.pull_request.head.repo.full_name }}" == "canonical/rockcraft" ]; then
-              echo "Error: UBUNTU_PRO_TOKEN is not set."
-              exit 1
-            else
-              echo "Warning: UBUNTU_PRO_TOKEN is not set. Skipping Pro tests"
-              exit 0
-            fi
-          fi
-          spread google:tests/spread/pro/
+      #      - name: Run Ubuntu Pro spread tests
+      #        env:
+      #          UBUNTU_PRO_TOKEN: ${{ secrets.UBUNTU_PRO_TOKEN }}
+      #        run: |
+      #          if [ -z "$UBUNTU_PRO_TOKEN" ]; then
+      #            if [ "${{ github.event.pull_request.head.repo.full_name }}" == "canonical/rockcraft" ]; then
+      #              echo "Error: UBUNTU_PRO_TOKEN is not set."
+      #              exit 1
+      #            else
+      #              echo "Warning: UBUNTU_PRO_TOKEN is not set. Skipping Pro tests"
+      #              exit 0
+      #            fi
+      #          fi
+      #          spread google:tests/spread/pro/
 
       - name: Run source spread tests
         run: |
-          spread google:...tests...
+          spread openstack:...tests...
 
       - name: Discard spread workers
         if: always()
